// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return desktop;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtPnY6osXkhRA0FGAbCymRPrT8wG3HlBA',
    appId: '1:773114516465:web:b488823bcce67595d76a50',
    messagingSenderId: '773114516465',
    projectId: 'pats-project-12d69',
    authDomain: 'pats-project-12d69.firebaseapp.com',
    storageBucket: 'pats-project-12d69.appspot.com',
    measurementId: 'G-CW7HLH2YHE',
  );

  static const FirebaseOptions desktop = FirebaseOptions(
    apiKey: 'AIzaSyCtPnY6osXkhRA0FGAbCymRPrT8wG3HlBA',
    appId: '1:773114516465:web:b488823bcce67595d76a50',
    messagingSenderId: '773114516465',
    projectId: 'pats-project-12d69',
    authDomain: 'pats-project-12d69.firebaseapp.com',
    storageBucket: 'pats-project-12d69.appspot.com',
    measurementId: 'G-CW7HLH2YHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmsAbKgROcDpsxAc15mcyByhd4yr5NLxM',
    appId: '1:773114516465:android:068ad9bf19c6e5d7d76a50',
    messagingSenderId: '773114516465',
    projectId: 'pats-project-12d69',
    storageBucket: 'pats-project-12d69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN9THusuHjA5f2zrQ2i6wZP6gPdBkCJZA',
    appId: '1:773114516465:ios:881014effce50d8bd76a50',
    messagingSenderId: '773114516465',
    projectId: 'pats-project-12d69',
    storageBucket: 'pats-project-12d69.appspot.com',
    iosClientId:
        '773114516465-uqva8gu4fhmg3lhub60aanpeu5bsok96.apps.googleusercontent.com',
    iosBundleId: 'com.example.patsproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN9THusuHjA5f2zrQ2i6wZP6gPdBkCJZA',
    appId: '1:773114516465:ios:881014effce50d8bd76a50',
    messagingSenderId: '773114516465',
    projectId: 'pats-project-12d69',
    storageBucket: 'pats-project-12d69.appspot.com',
    iosClientId:
        '773114516465-uqva8gu4fhmg3lhub60aanpeu5bsok96.apps.googleusercontent.com',
    iosBundleId: 'com.example.patsproject',
  );
}
